CREATE TABLE meetingrooms (
    id INTEGER(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(25) NOT NULL,
    date VARCHAR(15) NOT NULL,
    startHour VARCHAR(6) NOT NULL,
    endHour VARCHAR(6) NOT NULL
);